### ISSUE TITLE
Peer:2:Peer Morning session

### ISSUE THREAD

**Issue by rammazzoti2000** [rammazzoti2000/personal_portfolio#12]
Leave your comments bellow

**Comment by nyatindopatrick** [comment]
Good work! very responsive and the overlays look nice👍. I have nothing more to add

**Comment by dili021** [comment]
- Nice work on the responsiveness!
I was looking for the equivalent of netlify forms for github but couldn't find anything helpful in a few minutes, you can dig to find something maybe, or just deploy your repo to netlify and follow further (very easy) [instructions](https://www.netlify.com/products/forms) to add a working contact form.

**Comment by adamclasic** [comment]
Impressive work.  The color scheme and the design are just awesome. :clap:
You can maybe increase the contrast for header and the footer by lowering the grey color of the text and icons to be slightly more white.
