### ISSUE TITLE
Mobile.btn has behavioral bug

### ISSUE THREAD

**Issue by hardikchopra242** [rammazzoti2000/personal_portfolio#35]
The problem is with the mobile-btn on the navbar when the website works for the mobile version.
When we click on the mobile-btn initially it displays the navigation list which is fine but when we click a second time on the button instead of just closing the nav list (nav. nav) it also takes us to the top of the page.

To conclude the problem is with the navigation bar's button on the mobile version of the website, clicking twice will take us to the top which is not intended.

I read the codebase and found the piece of code for this section in the directory as follows :
        public > js > init
In the init.js the section belongs to line number 40-50.

**Comment by rammazzoti2000** [comment]
@hardikchopra242  Do you want to take over an create a Pull Request with a fix for this issue?

**Comment by hardikchopra242** [comment]
@rammazzoti2000  No, I am still in my learning phase and not completed React or Jquery.
Thanks for asking.

**Comment by rammazzoti2000** [comment]
@hardikchopra242  Alright then, thank you for finding the bug, I will come with a fix as soon as I have time.

**Comment by w3bdesign** [comment]
Fixed in https://github.com/rammazzoti2000/personal_portfolio/pull/38
