### ISSUE TITLE
form connect to netlify

### ISSUE THREAD

**Issue by Ashish07s** [rammazzoti2000/personal_portfolio#47]
sir can u explain how to our webpage contact form data on directly get netlify dashboard.

**Comment by rammazzoti2000** [comment]
Depending on the language, usually they have a plugin and have to follow instructions on how to integrate it in your website.
https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/

**Comment by Ashish07s** [comment]
my form is same as u , i used ur form code so what i should do?

**Comment by rammazzoti2000** [comment]
I understand. What is your portfolio link

- Go to app.netlify.com and click sites

![image](https://user-images.githubusercontent.com/3244654/116079823-929dff80-a698-11eb-8e49-b34c02e13628.png)

- Click on your portfolio

![image](https://user-images.githubusercontent.com/3244654/116079988-cc6f0600-a698-11eb-91cf-652be71ce95b.png)

- At the top click on Forms

![image](https://user-images.githubusercontent.com/3244654/116080134-f9231d80-a698-11eb-8ec3-2ed266f914c3.png)

- Under Active Forms you should see your active form.

**Comment by Ashish07s** [comment]
[image: 2021-04-26 (1).png]

**Comment by Ashish07s** [comment]
I am Not getting forms..
form code like this , should I changes in code
[image: 2021-04-26 (2).png]

**Comment by rammazzoti2000** [comment]
Do you have a link to  your portfolio?

**Comment by rammazzoti2000** [comment]
The way I did it was with React stateful form
https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/ got to `Form Handling with a Stateful React Form` and compare it with https://github.com/rammazzoti2000/personal_portfolio/blob/development/src/Components/Contact.js

This is how I did it, maybe try to change the name of the form in the `handleSubmit` class method

**Comment by Ashish07s** [comment]
Can take one google meet

**Comment by rammazzoti2000** [comment]
Of course we could, send me the link

**Comment by Ashish07s** [comment]
Will we meet at 9 PM like Indian time?
i will share link after 8:30
thank u sir

**Comment by rammazzoti2000** [comment]
Sure, will talk later.
Don't call me Sir please, call Alex, a lot easier 😄 
Have a nice evening.

**Comment by Ashish07s** [comment]
We have a lot of wind here right now, so our light is gone, we'll meet when
the light comes on.

**Comment by rammazzoti2000** [comment]
I understand, no prob. See you later, and stay safe.

**Comment by Ashish07s** [comment]
https://meet.google.com/reb-srqn-tyi

join now sir...

**Comment by Ashish07s** [comment]
Sir Im waiting ......

**Comment by Ashish07s** [comment]
Im waiting Sir , Since half an hours...
join
 https://meet.google.com/reb-srqn-tyi

**Comment by rammazzoti2000** [comment]
Hey sorry, are you still there?
I will join right away

**Comment by Ashish07s** [comment]
I mean my name and my description there same as u but name changed...

**Comment by Ashish07s** [comment]
Hle Alex Im Buying one domain On hostenger Site. and I have to connect to
my Netlify website , What can I do?

**Comment by rammazzoti2000** [comment]
I wouldn't know, but to make the domain work you would have to manually configure you project on Netlify with the custom domain.
If you buy a custom domain from netlify platform directly, they will handle the entire configuration for you.

Anyway here a tutorial about custom domains on netlify, hope it helps, cheers :smile: 
https://docs.netlify.com/domains-https/custom-domains/

**Comment by Ashish07s** [comment]
It's working now

**Comment by rammazzoti2000** [comment]
Whoa!! Cool Ashish, great job.
What is your website now?

**Comment by Ashish07s** [comment]
ashishsasatte.tech

**Comment by Ashish07s** [comment]
..[image: 2021-04-28 (2).png][image: 2021-04-28.png]

I have one problem sir, Observe  2 Screenshots , the scroll button is not
visible on my website..so help me
how to scroll button visible ... u can check my website(ashishsasatte.tech)
and Ur website , and u get difference...
help me .
