### ISSUE TITLE
I Have Connect Php page with my portfolio

### ISSUE THREAD

**Issue by Ashish07s** [rammazzoti2000/personal_portfolio#53]
Hiii Im ashish ,
Is there my one php project gallery, and I have to connect with my portfolio website, so how to connect this.

**Comment by Ashish07s** [comment]
how to Attach index.php file to this portfolio, like how to php and react use same project

**Comment by rammazzoti2000** [comment]
Hello @Ashish07s,

Honestly I have never used PHP inside react, but if you look on Google there are many tutorials on how to do it.

Checkout this link on medium, maybe is what you're looking for.
https://davisonpro.medium.com/an-advanced-guide-on-setting-up-a-react-and-php-web-app-acaedb21ab3a

**Comment by Ashish07s** [comment]
can u help me about this beacause I'll try but its not working so I got some issue help me

**Comment by Ashish07s** [comment]
But I have to add one page on tyat website only so that tutorials Im not getting what is says 
 can u meet with me now on that topic how to connect php with react

**Comment by rammazzoti2000** [comment]
@Ashish07s,

Ok we could meet and see what's going on.
Share a link to the meeting when you are ready.

**Comment by Ashish07s** [comment]
https://meet.google.com/msf-ajut-prb

meet link
